apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        rollout-timestamp: {{ .Values.deployTimestamp | quote }}
    spec:
      containers:
        - name: my-backend-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
